//
//  LikeInteractor.swift
//  aywa
//
//  Created by Zoeb on 22/12/17.
//  Copyright (c) 2017 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LikeBusinessLogic
{
  func doSomething(request: Like.Something.Request)
}

protocol LikeDataStore
{
  //var name: String { get set }
}

class LikeInteractor: LikeBusinessLogic, LikeDataStore
{
  var presenter: LikePresentationLogic?
  var worker: LikeWorker?
  //var name: String = ""
  
  // MARK: Do Like
  
  func doSomething(request: Like.Something.Request)
  {
    worker = LikeWorker()
    worker?.doSomeWork()
    
    let response = Like.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
