//
//  LikePresenter.swift
//  aywa
//
//  Created by Bestpeers on 22/12/17.
//  Copyright (c) 2017 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LikePresentationLogic
{
  func presentSomething(response: Like.Something.Response)
}

class LikePresenter: LikePresentationLogic
{
  weak var viewController: LikeDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Like.Something.Response)
  {
    let viewModel = Like.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
