//
//  NotificationsPresenter.swift
//  aywa
//
//  Created by Bestpeers on 18/01/18.
//  Copyright (c) 2018 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NotificationsPresentationLogic
{
  func presentSomething(response: Notifications.Something.Response)
}

class NotificationsPresenter: NotificationsPresentationLogic
{
  weak var viewController: NotificationsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Notifications.Something.Response)
  {
    let viewModel = Notifications.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
