//
//  MoviesInteractor.swift
//  aywa
//
//  Created by Bestpeers on 09/01/18.
//  Copyright (c) 2018 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MoviesBusinessLogic
{
  func doSomething(request: Movies.Something.Request)
}

protocol MoviesDataStore
{
  //var name: String { get set }
}

class MoviesInteractor: MoviesBusinessLogic, MoviesDataStore
{
  var presenter: MoviesPresentationLogic?
  var worker: MoviesWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Movies.Something.Request)
  {
    worker = MoviesWorker()
    worker?.doSomeWork()
    
    let response = Movies.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
