//
//  MoviesInteractor.swift
//  aywa
//
//  Created by Bestpeers on 09/01/18.
//  Copyright (c) 2018 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MoviesBusinessLogic
{
    func doMovies(request: Movies.MyListMovies.Request)
}

protocol MoviesDataStore
{
    //var name: String { get set }
}

class MoviesInteractor: MoviesBusinessLogic, MoviesDataStore
{
    var presenter: MoviesPresentationLogic?
    var worker: MoviesWorker?
    
    // MARK:- Do Movies Interactor
    func doMovies(request: Movies.MyListMovies.Request)
    {
        worker = MoviesWorker()
        worker?.doMoviesWork(request: request, success: { (response) in
            print(response)
            self.presenter?.presentResponse(response: response)
        }, fail: { (response) in
            self.presenter?.presentError(response: response)
        })
    }
}
