//
//  MoviesPresenter.swift
//  aywa
//
//  Created by Bestpeers on 09/01/18.
//  Copyright (c) 2018 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MoviesPresentationLogic
{
  func presentSomething(response: Movies.Something.Response)
}

class MoviesPresenter: MoviesPresentationLogic
{
  weak var viewController: MoviesDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Movies.Something.Response)
  {
    let viewModel = Movies.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
