//
//  MoviesPresenter.swift
//  aywa
//
//  Created by Bestpeers on 09/01/18.
//  Copyright (c) 2018 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MoviesPresentationLogic
{
    func presentError(response:  Movies.MyListMovies.Response)
    func presentResponse(response:  [Movies.MyListMovies.Response])
}

class MoviesPresenter: MoviesPresentationLogic
{
  weak var viewController: MoviesDisplayLogic?
  
  // MARK: Do  Handle Response For Movies
    func presentError(response:  Movies.MyListMovies.Response){
        viewController?.displayMyListMoviesError(response: response)
    }
    func presentResponse(response:  [Movies.MyListMovies.Response]){
        viewController?.displayMyListMoviesResponse(response: response)
    }
}
