//
//  FacebookWorker.swift
//  aywa
//
//  Created by Bestpeers on 28/12/17.
//  Copyright (c) 2017 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import FBSDKLoginKit

class FacebookWorker
{
    let facebookReadPermissions = ["email"] //["public_profile", "email", "user_friends"]
    
    //MARK: Do Facebook Login
    func doFacebookLogin(completionHandler: @escaping (Dictionary< String, Any>) -> Void )   {
        let fbLoginManager : FBSDKLoginManager = FBSDKLoginManager()
        
        fbLoginManager.logIn(withReadPermissions: self.facebookReadPermissions, from: UIViewController()) { (result, error) in
            if (error == nil){
                let fbloginresult : FBSDKLoginManagerLoginResult = result!
                if fbloginresult.grantedPermissions != nil {
                    if(fbloginresult.grantedPermissions.contains("email"))
                    {
                        let fbToken: String! = result!.token.tokenString
                         //fbLoginManager.logOut()
                        if((FBSDKAccessToken.current()) != nil){
                            FBSDKGraphRequest(graphPath: "me", parameters: ["fields": "id, name, first_name, last_name, picture.type(large), email"]).start(completionHandler: { (connection, result, error) -> Void in
                                if (error == nil){
                                    let dict = result as! [String : AnyObject]
                                    let dicUserDetails: Dictionary< String, Any>!
                                    if let email = dict["email"]! as? String{
                                        dicUserDetails = [Constants.kFbToken: fbToken, Constants.kEmailKey: email]
                                    }
                                    else{
                                        dicUserDetails = [Constants.kFbToken: fbToken]
                                    }
                                    print(dicUserDetails)
                                    completionHandler(dicUserDetails)
                                }
                            })
                        }
                    }
                }
                
            }
        }
    }
    
}
