//
//  AlertPresenter.swift
//  aywa
//
//  Created by Zoeb on 22/12/17.
//  Copyright (c) 2017 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AlertPresentationLogic
{
  func presentSomething(response: Alert.Something.Response)
}

class AlertPresenter: AlertPresentationLogic
{
  weak var viewController: AlertDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Alert.Something.Response)
  {
    let viewModel = Alert.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
