//
//  AlertWorker.swift
//  aywa
//
//  Created by Bestpeers on 22/12/17.
//  Copyright (c) 2017 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class AlertWorker
{
  func doSomeWork()
  {
  }
}
