//
//  AlertInteractor.swift
//  aywa
//
//  Created by Zoeb on 22/12/17.
//  Copyright (c) 2017 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AlertBusinessLogic
{
  func doSomething(request: Alert.Something.Request)
}

protocol AlertDataStore
{
  //var name: String { get set }
}

class AlertInteractor: AlertBusinessLogic, AlertDataStore
{
  var presenter: AlertPresentationLogic?
  var worker: AlertWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Alert.Something.Request)
  {
    worker = AlertWorker()
    worker?.doSomeWork()
    
    let response = Alert.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
