//
//  CategoryPresenter.swift
//  aywa
//
//  Created by Zoeb on 22/12/17.
//  Copyright (c) 2017 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CategoryPresentationLogic
{
  func presentSomething(response: Category.Something.Response)
}

class CategoryPresenter: CategoryPresentationLogic
{
  weak var viewController: CategoryDisplayLogic?
  
  // MARK: Do  Category
  
  func presentSomething(response: Category.Something.Response)
  {
    let viewModel = Category.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
