//
//  CategoryInteractor.swift
//  aywa
//
//  Created by Zoeb on 22/12/17.
//  Copyright (c) 2017 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CategoryBusinessLogic
{
  func doSomething(request: Category.Something.Request)
}

protocol CategoryDataStore
{
  //var name: String { get set }
}

class CategoryInteractor: CategoryBusinessLogic, CategoryDataStore
{
  var presenter: CategoryPresentationLogic?
  var worker: CategoryWorker?
  //var name: String = ""
  
  // MARK: Do  Category
  
  func doSomething(request: Category.Something.Request)
  {
    worker = CategoryWorker()
    worker?.doSomeWork()
    
    let response = Category.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
