//
//  HomeSliderBannerViewController.swift
//  aywa
//
//  Created by Bestpeers on 20/12/17.
//  Copyright (c) 2017 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeSliderBannerDisplayLogic: class
{
    //func displaySomething(viewModel: HomeSliderBanner.Something.ViewModel)
}

class HomeSliderBannerViewController: UIViewController, HomeSliderBannerDisplayLogic
{
    var interactor: HomeSliderBannerBusinessLogic?
    var router: (NSObjectProtocol & HomeSliderBannerRoutingLogic & HomeSliderBannerDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = HomeSliderBannerInteractor()
        let presenter = HomeSliderBannerPresenter()
        let router = HomeSliderBannerRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        
        let nib = UINib(nibName: Identifiers.homeAdvertCollectionCell, bundle: Bundle.main)
        homeHeaderCollectionView.register(nib, forCellWithReuseIdentifier: Identifiers.homeAdvertCollectionCell)
    }
    
    
    // MARK: Do something
    
    @IBOutlet weak var homeHeaderCollectionView: UICollectionView!
   
    @IBAction func tvShareButtonTapped(_ sender: Any) {
        doTVShareAction()
    }
    @IBAction func menuButtonTapped(_ sender: Any) {
        doMenuAction()
    }
    
  
    //MARK: Do TV Share Action
    func doTVShareAction() {
        print("Perform TV Share Action")
    }
    //MARK: Do Menu Action
    func doMenuAction() {
        print("Perform Menu Action")
    }
}

extension HomeSliderBannerViewController: UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
    //MARK:- UICollectionView methods
    //MARK: Datasource
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return 5
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell: HomeHeaderAdvertisementCollectionViewCell = collectionView.dequeueReusableCell(withReuseIdentifier: Identifiers.homeAdvertCollectionCell, for: indexPath) as! HomeHeaderAdvertisementCollectionViewCell
        return cell
    }
    
    //MARK: Delegate
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        return CGSize(width: self.view.frame.size.width, height: self.view.frame.size.height)
    }
}
