//
//  HomeSliderBannerRouter.swift
//  aywa
//
//  Created by Zoeb on 20/12/17.
//  Copyright (c) 2017 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeSliderBannerRoutingLogic
{
    //func routeToHomeViewController()
}

protocol HomeSliderBannerDataPassing
{
    var dataStore: HomeSliderBannerDataStore? { get }
}

class HomeSliderBannerRouter: NSObject, HomeSliderBannerRoutingLogic, HomeSliderBannerDataPassing
{
    weak var viewController: HomeSliderBannerViewController?
    var dataStore: HomeSliderBannerDataStore?
    
    // MARK: Routing
    func routeToHomeViewController(){
       // let destinationViewController = PlansViewController.create(of: .UniversalStoryboard)
        //navigateToViewController(source: viewController!, destination: destinationViewController)
    }
    
    // MARK: Navigation
    
//    func navigateToViewController(source: HomeSliderBannerViewController, destination: UIViewController)
//    {
//        source.bpPush(viewController: destination)
//    }
    
}
