//
//  HomeSliderBannerInteractor.swift
//  aywa
//
//  Created by Zoeb on 20/12/17.
//  Copyright (c) 2017 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeSliderBannerBusinessLogic
{
    func doCallSliderBannerAPI(request: HomeSliderBanner.SliderBanner.Request)
}

protocol HomeSliderBannerDataStore
{
    //var name: String { get set }
}

class HomeSliderBannerInteractor: HomeSliderBannerBusinessLogic, HomeSliderBannerDataStore
{
    var presenter: HomeSliderBannerPresentationLogic?
    var worker: HomeSliderBannerWorker?
    var securityStorageWorker = SecurityStorageWorker()
    
    
    // MARK: Do CallSliderBannerAPI
    
    func doCallSliderBannerAPI(request: HomeSliderBanner.SliderBanner.Request)
    {
        worker = HomeSliderBannerWorker()
        worker?.sliderBanner(request: request, success: { (response) in
            print(response)
            self.presenter?.presentNextScreen(response:response)
            
        }, fail: { (response) in
            self.presenter?.presentError(response: response)
        })
    }
}
