//
//  HomeSliderBannerInteractor.swift
//  aywa
//
//  Created by Bestpeers on 20/12/17.
//  Copyright (c) 2017 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeSliderBannerBusinessLogic
{
 // func doSomething(request: HomeSliderBanner.Something.Request)
}

protocol HomeSliderBannerDataStore
{
  //var name: String { get set }
}

class HomeSliderBannerInteractor: HomeSliderBannerBusinessLogic, HomeSliderBannerDataStore
{
  var presenter: HomeSliderBannerPresentationLogic?
  var worker: HomeSliderBannerWorker?
  //var name: String = ""
  
  // MARK: Do something
  
//  func doSomething(request: HomeSliderBanner.Something.Request)
//  {
//    worker = HomeSliderBannerWorker()
//    worker?.doSomeWork()
//
//    let response = HomeSliderBanner.Something.Response()
//    presenter?.presentSomething(response: response)
//  }
}
