//
//  LandingPresenter.swift
//  aywa
//
//  Created by Zoeb on 11/12/17.
//  Copyright (c) 2017 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LandingPresentationLogic
{
    func presentError(response: Landing.JWTToken.Response)
    func presentNextScreen()
}

class LandingPresenter: LandingPresentationLogic
{
  weak var viewController: LandingDisplayLogic?
  
  // MARK: Fetch Token
    
    func presentError(response: Landing.JWTToken.Response)
    {
        viewController?.displayError(response: response)
    }
    
    func presentNextScreen()
    {
        viewController?.displayNextScreen()
    }
}
