//
//  LandingRouter.swift
//  aywa
//
//  Created by Zoeb on 11/12/17.
//  Copyright (c) 2017 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LandingRoutingLogic
{
    func routeToLogin()
    func routeToSignup()
    func routeToTabBar()
}

class LandingRouter: NSObject, LandingRoutingLogic
{
    weak var viewController: LandingViewController?
    
    // MARK: Routing
    
    func routeToLogin() {
        let destinationVC = LoginViewController.create(of: .UniversalStoryboard)
        navigateToSomewhere(source: viewController!, destination: destinationVC)
    }
    
    func routeToSignup() {
        let destinationVC = SignupViewController.create(of: .UniversalStoryboard)
        navigateToSomewhere(source: viewController!, destination: destinationVC)
    }
    
    func routeToTabBar() {
        ApplicationDelegate.setTabBarAsRootViewController()
    }
    
    // MARK: Navigation
    
    func navigateToSomewhere(source: LandingViewController, destination: UIViewController)
    {
        source.navigationController?.pushViewController(destination, animated: false)
    }
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: LandingDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
