//
//  LandingInteractor.swift
//  aywa
//
//  Created by Zoeb on 11/12/17.
//  Copyright (c) 2017 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LandingBusinessLogic
{
  func fetchToken(request: Landing.JWTToken.Request)
}

protocol LandingDataStore
{
  //var name: String { get set }
}

class LandingInteractor: LandingBusinessLogic, LandingDataStore
{
  var presenter: LandingPresentationLogic?
  var worker: LandingWorker?
  //var name: String = ""
  
  // MARK: Fetch JWT Token
  
  func fetchToken(request: Landing.JWTToken.Request)
  {
    worker = LandingWorker()
    worker?.fetchJWTToken(request: request, success: { (response) in
        self.presenter?.presentNextScreen(viewModel: response)
        
    }, fail: { (response) in
        self.presenter?.presentError(response: response)
        
    })
  }
}
