//
//  LandingModels.swift
//  aywa
//
//  Created by Zoeb on 11/12/17.
//  Copyright (c) 2017 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

let tokenURL = "/token"
let secret = "Secret"

enum Landing
{
  // MARK: Use cases
  
  enum JWTToken
  {
    struct Request
    {
        func baseRequest() -> BaseRequest {
            
            let baseRequest = BaseRequest()
            baseRequest.urlPath = tokenURL
            baseRequest.parameters[Constants.kApiKey] = Constants.kApiKeyValue
            baseRequest.parameters[secret] = Constants.kApiKeyValue
            baseRequest.parameters[Constants.deviceIdentifier] = UserDefaults.standard.string(forKey: Constants.deviceIdentifier) ?? (UIDevice.current.identifierForVendor?.uuidString)!
            return baseRequest
        }
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}
