//
//  TVInteractor.swift
//  aywa
//
//  Created by Bestpeers on 09/01/18.
//  Copyright (c) 2018 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TVBusinessLogic
{
  func doSomething(request: TV.Something.Request)
}

protocol TVDataStore
{
  //var name: String { get set }
}

class TVInteractor: TVBusinessLogic, TVDataStore
{
  var presenter: TVPresentationLogic?
  var worker: TVWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: TV.Something.Request)
  {
    worker = TVWorker()
    worker?.doSomeWork()
    
    let response = TV.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
