//
//  TVPresenter.swift
//  aywa
//
//  Created by Bestpeers on 09/01/18.
//  Copyright (c) 2018 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TVPresentationLogic
{
  func presentSomething(response: TV.Something.Response)
}

class TVPresenter: TVPresentationLogic
{
  weak var viewController: TVDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: TV.Something.Response)
  {
    let viewModel = TV.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
