//
//  ForgotPasswordPresenter.swift
//  aywa
//
//  Created by Bestpeers on 29/12/17.
//  Copyright (c) 2017 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ForgotPasswordPresentationLogic
{
    func presentError(response: Common.Response)
    func presentNewPasswordScreen()
    
}

class ForgotPasswordPresenter: ForgotPasswordPresentationLogic
{
  weak var viewController: ForgotPasswordDisplayLogic?
  
  // MARK: Do something
    func presentError(response: Common.Response)
    {
        viewController?.displayError(response: response)
        Utils.showAlertWith(title: "Aywa!", message: response.message!, inController: viewController as! UIViewController)
    }
    
    func presentNewPasswordScreen()
    {
        viewController?.displayForgotPasswordResponse()
    }
}
