//
//  ForgotPasswordWorker.swift
//  aywa
//
//  Created by Bestpeers on 29/12/17.
//  Copyright (c) 2017 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ForgotPasswordWorker: BaseWorker
{
    func doForgottenPasswordWork(request:ForgotPassword.ResetPasswod.Request, success:@escaping(commonResponseHandler), fail:@escaping(commonResponseHandler))
    {
        //call network etc.
        let manager = RequestManager()
        
        manager.performPostAPI(request: request.baseRequest()) { (status, response) in
            self.handleCommonResponse(success: success, fail: fail, status: status, response: response)
        }
    }
}
