//
//  ForgotPasswordModels.swift
//  aywa
//
//  Created by Bestpeers on 29/12/17.
//  Copyright (c) 2017 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
let resetPasswordURL = "/account/password_reset"

enum ForgotPassword
{
    // MARK: Use cases
    
    enum ResetPasswod
    {
        struct Request
        {
            var email :String?
            
            func baseRequest() -> BaseRequest {
                let baseRequest = BaseRequest()
                baseRequest.urlPath = resetPasswordURL
                baseRequest.parameters[Constants.kEmailKey] = email
                baseRequest.parameters[BaseRequest.hasNullResponse] = true
                return baseRequest
            }
        }
    }
}
