//
//  TVShowsInteractor.swift
//  aywa
//
//  Created by Bestpeers on 09/01/18.
//  Copyright (c) 2018 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TVShowsBusinessLogic
{
  func doTVShows(request: TVShows.MyListShows.Request)
}

protocol TVShowsDataStore
{
  //var name: String { get set }
}

class TVShowsInteractor: TVShowsBusinessLogic, TVShowsDataStore
{
  var presenter: TVShowsPresentationLogic?
  var worker: TVShowsWorker?
  
  // MARK: Do TVShows Interactor
  
  func doTVShows(request: TVShows.MyListShows.Request)
  {
    worker = TVShowsWorker()
    worker?.doTVShowsWork(request: request, success: { (response) in
        print(response)
        self.presenter?.presentResponse(response: response)
    }, fail: { (response) in
        self.presenter?.presentError(response: response)
    })
  }
}
