//
//  TVShowsInteractor.swift
//  aywa
//
//  Created by Bestpeers on 09/01/18.
//  Copyright (c) 2018 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TVShowsBusinessLogic
{
  func doSomething(request: TVShows.Something.Request)
}

protocol TVShowsDataStore
{
  //var name: String { get set }
}

class TVShowsInteractor: TVShowsBusinessLogic, TVShowsDataStore
{
  var presenter: TVShowsPresentationLogic?
  var worker: TVShowsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: TVShows.Something.Request)
  {
    worker = TVShowsWorker()
    worker?.doSomeWork()
    
    let response = TVShows.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
