//
//  TVShowsPresenter.swift
//  aywa
//
//  Created by Bestpeers on 09/01/18.
//  Copyright (c) 2018 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TVShowsPresentationLogic
{
    func presentError(response:  TVShows.MyListShows.Response)
    func presentResponse(response:  [TVShows.MyListShows.Response])
}

class TVShowsPresenter: TVShowsPresentationLogic
{
  weak var viewController: TVShowsDisplayLogic?
  
  // MARK: Do TVShowsPresenter Handle response and Present
    func presentError(response:  TVShows.MyListShows.Response){
        viewController?.displayMyListShowsError(response: response)
    }
    func presentResponse(response:  [TVShows.MyListShows.Response]){
        viewController?.displayMyListShowsResponse(response: response)
    }
}
