//
//  SignupInteractor.swift
//  aywa
//
//  Created by Zoeb on 16/12/17.
//  Copyright (c) 2017 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignupBusinessLogic
{
    func doSignup(request: Signup.Register.Request)
}

protocol SignupDataStore
{
    //var name: String { get set }
}

class SignupInteractor: SignupBusinessLogic, SignupDataStore
{
    var presenter: SignupPresentationLogic?
    var worker: SignupWorker?
    var securityStorageWorker = SecurityStorageWorker()
    
    // MARK: Do Signup
    
    func doSignup(request: Signup.Register.Request)
    {
        if request.email == nil || request.password == nil || request.name == nil {
            return (presenter?.presentError(response: Landing.JWTToken.Response(message: "Fields may not be empty.")!))!
        }
        
        worker = SignupWorker()
        worker?.register(request: request, success: { (response) in
            print(response)
            if self.securityStorageWorker.storeAccessTokenResponse(response: response) {
                self.presenter?.presentNextScreen()
            }
            
        }, fail: { (response) in
            self.presenter?.presentError(response: response)
            
        })
        
    }
}
