//
//  SignupModels.swift
//  aywa
//
//  Created by Zoeb on 16/12/17.
//  Copyright (c) 2017 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

let registrationURL = "/registration"

enum Signup
{
  // MARK: Use cases
  
  enum Register
  {
    struct Request
    {
        var email :String?
        var password :String?
        var name :String?
        var deviceIdentifier:String?
        var deviceType :Int?
        var birthday :Date?
        var ageGroup :String?
        var gender :String?
        var country :String?
        var countryName :String?
        var phone :String?
        var ipAddress :String?
        
        func baseRequest() -> BaseRequest {
            
            let baseRequest = BaseRequest()
            baseRequest.urlPath = registrationURL
            baseRequest.parameters[Constants.kApiKey] = Constants.kApiKeyValue
            baseRequest.parameters[secret] = Constants.kApiKeyValue
            baseRequest.parameters[Constants.deviceIdentifier] = deviceIdentifier
            return baseRequest
        }
    }
  }
}
