//
//  SignupPresenter.swift
//  aywa
//
//  Created by Zoeb on 16/12/17.
//  Copyright (c) 2017 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignupPresentationLogic
{
    func presentError(response: Landing.JWTToken.Response)
    func presentNextScreen()
}

class SignupPresenter: SignupPresentationLogic
{
  weak var viewController: SignupDisplayLogic?
  
  // MARK: Do Signup
    
    func presentError(response: Landing.JWTToken.Response)
    {
        viewController?.displayError(response: response)
    }
    
    func presentNextScreen()
    {
        viewController?.displayHomeScreen()
    }
}
