//
//  NetworksPresenter.swift
//  aywa
//
//  Created by Bestpeers on 09/01/18.
//  Copyright (c) 2018 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NetworksPresentationLogic
{
  func presentSomething(response: Networks.Something.Response)
}

class NetworksPresenter: NetworksPresentationLogic
{
  weak var viewController: NetworksDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Networks.Something.Response)
  {
    let viewModel = Networks.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
