//
//  PlansViewController.swift
//  aywa
//
//  Created by Bestpeers on 18/01/18.
//  Copyright (c) 2018 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PlansDisplayLogic: class
{
  func displaySomething(viewModel: Plans.Something.ViewModel)
}

class PlansViewController: UIViewController, PlansDisplayLogic
{
  var interactor: PlansBusinessLogic?
  var router: (NSObjectProtocol & PlansRoutingLogic & PlansDataPassing)?
    
    var selectedCellIndex = 0

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = PlansInteractor()
    let presenter = PlansPresenter()
    let router = PlansRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
    }
    func initialiseView() {
        // Initialization code
        navigationBarWithLeftSideTitle(isTitle: false, titleName: LocaleKeys.kPlans)
        
        let nib  = UINib(nibName: Identifiers.planTableViewCell, bundle: Bundle.main)
        tableView.register(nib, forCellReuseIdentifier: Identifiers.planTableViewCell)
    }
    // MARK: Routing
    
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    initialiseView()
  }
  
  // MARK: Do something
  
    @IBOutlet weak var tableView: UITableView!
  
  func doSomething()
  {
    let request = Plans.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: Plans.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}

extension PlansViewController: UITableViewDelegate, UITableViewDataSource {
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return 3
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        if section == 0 || section == 2 {
            return 1
        } else {
            return 3
        }
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if indexPath.section == 0 {
            return tableView.dequeueReusableCell(withIdentifier: Identifiers.selectPlanTableViewCell, for: indexPath)
        } else if indexPath.section == 2 {
            return tableView.dequeueReusableCell(withIdentifier: Identifiers.continuePlanTableViewCell, for: indexPath)
        } else {
            let cell = tableView.dequeueReusableCell(withIdentifier: Identifiers.planTableViewCell, for: indexPath) as! PlanTableViewCell
            cell.isSelectedPlan = indexPath.row == selectedCellIndex
            return cell
        }
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        selectedCellIndex = indexPath.row
        tableView.reloadData()
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        if indexPath.section == 0 {
            return 75
        } else if indexPath.section == 2 {
            return 85
        } else {
            return 140
        }
    }
    
}
