//
//  PlansViewController.swift
//  aywa
//
//  Created by Bestpeers on 18/01/18.
//  Copyright (c) 2018 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PlansDisplayLogic: class
{
  func displaySomething(viewModel: Plans.Something.ViewModel)
}

class PlansViewController: UIViewController, PlansDisplayLogic
{
  var interactor: PlansBusinessLogic?
  var router: (NSObjectProtocol & PlansRoutingLogic & PlansDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = PlansInteractor()
    let presenter = PlansPresenter()
    let router = PlansRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
    func initialiseView() {
        // Initialization code
        
//        let nib = UINib(nibName: Identifiers.homeImageHorizontalCollectionViewCell, bundle: Bundle.main)
//        collectionView.register(nib, forCellWithReuseIdentifier: Identifiers.homeImageHorizontalCollectionViewCell)
//
//        self.collectionView.isHidden = true
//        self.labelForAddShows.isHidden = true
//        self.buttonForAddShows.isHidden = true
//        if setTitle.isEmpty {
//            navigationBarWithLeftSideTitle(isTitle: false, titleName: "Shows")
//            // Call Shows Request
//            doMyListShows()
//
//        }else{
//            navigationBarWithLeftSideTitle(isTitle: false, titleName: setTitle)
//            showCollectionView()
//        }
          navigationBarWithLeftSideTitle(isTitle: false, titleName: "Plans")
    }
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = Plans.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: Plans.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
