//
//  PlansInteractor.swift
//  aywa
//
//  Created by Bestpeers on 18/01/18.
//  Copyright (c) 2018 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PlansBusinessLogic
{
  func doSomething(request: Plans.Something.Request)
}

protocol PlansDataStore
{
  //var name: String { get set }
}

class PlansInteractor: PlansBusinessLogic, PlansDataStore
{
  var presenter: PlansPresentationLogic?
  var worker: PlansWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Plans.Something.Request)
  {
    worker = PlansWorker()
    worker?.doSomeWork()
    
    let response = Plans.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
