//
//  LoginWorker.swift
//  aywa
//
//  Created by Zoeb on 18/12/17.
//  Copyright (c) 2017 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LoginWorker: BaseWorker
{
    func signin(request:Login.Signin.Request, success:@escaping(accessTokenResponseHandler), fail:@escaping(accessTokenResponseHandler))
    {
        //call network etc.
        let manager = RequestManager()
        
        manager.fetchJWTToken(request: request.baseRequest()) { (status, response) in
            self.handleTokenResponse(success: success, fail: fail, status: status, response: response)
        }
    }
}
