//
//  LoginModels.swift
//  aywa
//
//  Created by Zoeb on 18/12/17.
//  Copyright (c) 2017 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
let loginURL = "/account/login"
let facebookURL = "/account/login/facebook"

enum Login
{
    // MARK: Use cases
    
    enum Signin
    {
        struct Request
        {
            var email :String?
            var password :String?
            var deviceIdentifier:String?
            var deviceType :Int?
            
            func baseRequest() -> BaseRequest {
                let baseRequest = BaseRequest()
                baseRequest.urlPath = loginURL
                baseRequest.parameters[Constants.kUserName] = email
                baseRequest.parameters[Constants.kPasswordKey] = password
                baseRequest.parameters[Constants.deviceIdentifier] = deviceIdentifier
                baseRequest.parameters[Constants.DeviceTypeKey] = deviceType
                return baseRequest
            }
        }
        struct FacebookLoginRequest
        {
            var token :String?
            var deviceIdentifier:String?
            var deviceType :Int?
            
            func baseRequest() -> BaseRequest {
                let baseRequest = BaseRequest()
                baseRequest.urlPath = facebookURL
                baseRequest.parameters[Constants.kFbToken] = token
                baseRequest.parameters[Constants.deviceIdentifier] = deviceIdentifier
                baseRequest.parameters[Constants.DeviceTypeKey] = deviceType
                return baseRequest
            }
        }
    }
}
