//
//  HomeInteractor.swift
//  aywa
//
//  Created by Bestpeers on 19/12/17.
//  Copyright (c) 2017 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
    func doSectionAPI(request: Home.Section.Request)
}

protocol HomeDataStore
{
  //var name: String { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
    
  var presenter: HomePresentationLogic?
  var worker: HomeWorker?
  //var name: String = ""
  
  // MARK: Do something
  
//  func doSomething(request: Home.Something.Request)
//  {
//    worker = HomeWorker()
//    worker?.doSomeWork()
//
//    let response = Home.Something.Response()
//    presenter?.presentSomething(response: response)
//  }
    
    func doSectionAPI(request: Home.Section.Request) {
        var message:String = Constants.kErrorMessage
        worker = HomeWorker()
        worker?.homeSection(request: request, success: { (response) in
            print(response)
            self.presenter?.presentNextScreen(response:response)
            
        }, fail: { (response) in
            self.presenter?.presentError(response: Home.Section.Response(message: message)!)
        })
    }
}
