//
//  HomeRouter.swift
//  aywa
//
//  Created by Zoeb on 19/12/17.
//  Copyright (c) 2017 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic
{
    func routeToMoveHomeBannerViewController()
}

protocol HomeDataPassing
{
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing
{
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?
    
    // MARK: Routing
    
    func routeToMoveHomeBannerViewController(){
        let destinationVC = HomeSliderBannerViewController.create(of: .UniversalStoryboard)
        passDataToHomeSliderBannerCatalogId(source: viewController!, destination: destinationVC)
        addHomeBanner(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    func addHomeBanner(source: HomeViewController, destination: UIViewController){
        source.homeHeader = destination
        source.homeHeader.view.bounds.size = CGSize(width: source.view.frame.size.width, height: source.view.frame.size.width * (236/source.view.frame.size.width))
        source.tableView.tableHeaderView = source.homeHeader.view
    }
    
    // MARK: Passing data
    // For Home Banner
    func passDataToHomeSliderBannerCatalogId(source: HomeViewController, destination: HomeSliderBannerViewController){
        destination.catalogIdForHomeSlider = source.catalogIdForHomeSection
    }
}
