//
//  HomeWorker.swift
//  aywa
//
//  Created by Bestpeers on 19/12/17.
//  Copyright (c) 2017 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
typealias homeSectionSuccessResponseHandler = (_ response:[Home.Section.Response]) ->()
typealias homeSectionFailureResponseHandler = (_ response:Home.Section.Response) ->()

class HomeWorker
{
    func homeSection(request:Home.Section.Request, success:@escaping(homeSectionSuccessResponseHandler), fail:@escaping(homeSectionFailureResponseHandler))
    {
        //call network etc.
        let manager = RequestManager()
        manager.fetchSection(request: request.baseRequest()) { (status, response) in
            self.handleSectionResponse(success: success, fail: fail, status: status, response: response)

        }
    }
    
    func handleSectionResponse(success:@escaping(homeSectionSuccessResponseHandler), fail:@escaping(homeSectionFailureResponseHandler), status: Bool, response: Any?) {
        var message:String = Constants.kErrorMessage
        if status {
            if let result = response as? [Home.Section.Response] {
                success(result)
                return
            }
        }
        else {
            if let result = response as? Home.Section.Response {
                fail(result)
                return
            }
            else
            {
                if let result = response as? String {
                    message = result
                }
            }
        }
        fail(Home.Section.Response(message: message)!)
    }
}
