//
//  HomePresenter.swift
//  aywa
//
//  Created by Bestpeers on 19/12/17.
//  Copyright (c) 2017 Alpha Solutions. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
    func presentError(response: Landing.JWTToken.Response)
    func presentNextScreen()
}

class HomePresenter: HomePresentationLogic
{
  weak var viewController: HomeDisplayLogic?
  
  // MARK: Do Slider
  
    
    func presentError(response: Landing.JWTToken.Response)
    {
        viewController?.displayError(response: response)
    }
    
    func presentNextScreen()
    {
        viewController?.displayHomeScreen()
    }
}
